services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: whats_new
      POSTGRES_USER: ${Database_Username}
      POSTGRES_PASSWORD: ${Database_Password}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${Database_Username} -d whats_new"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      SENDGRID_API_KEY: "${SENDGRID_API_KEY}"
      Database_Name: "${Database_Name}"
      Database_Username: "${Database_Username}"
      Database_Password: "${Database_Password}"
      NEWS_API_KEY: "${NEWS_API_KEY}"
      Gemini_API_KEY: "${Gemini_API_KEY}"
      host: db
volumes:
  postgres_data: